plugins {
  id 'java'
  id 'eclipse'
  id 'maven-publish'
  id 'signing'
  id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

if (JavaVersion.current().isJava8Compatible()) {
  allprojects {
    tasks.withType(Javadoc) {
      options.addStringOption('Xdoclint:none', '-quiet')
    }
  }
}

// The project version is controlled externally by the "version.sh" script.
def getVersion = { ->
  def stdout = new ByteArrayOutputStream()
  exec {
    commandLine 'bash', 'version.sh'
    standardOutput = stdout
  }
  return stdout.toString().trim()
}

def validateVersion = { version ->
  def matcher = version =~/^(\d+\.)?(\d+\.)?(\d+\.)?(\d+)(-SNAPSHOT){0,1}$/
  return matcher.matches() || System.getenv('FORCE_PUBLISH')
}

def getBranch = { ->
  def branch = System.getenv('CIRCLE_BRANCH')
      ?: System.getenv('GITHUB_HEAD_REF')
      ?: System.getenv('GITHUB_REF_NAME')
      ?: System.getenv('BRANCH_NAME')
      ?: System.getenv('CI_COMMIT_BRANCH')
      ?: System.getenv('GIT_BRANCH')
  if (branch) {
    return branch
  }
  def stdout = new ByteArrayOutputStream()
  exec {
    commandLine 'git', 'rev-parse', '--abbrev-ref', 'HEAD'
    standardOutput = stdout
  }
  return stdout.toString().trim()
}

group = 'com.cinchapi'
version  = getVersion()
ext.currentBranch = getBranch()

// Drop the build component from version number and use that for
// publishing
ext.mavenVersion = version.split('\\.')
ext.mavenVersion[3] = ext.mavenVersion[3].replaceAll("[0-9]+-", "-")
ext.mavenVersion[3] = ext.mavenVersion[3].replaceAll("[0-9]+", "").trim()
ext.mavenVersion = ext.mavenVersion.join(".").replace(".-", "-").replaceAll('\\.$', "")

ext.isReleasable = validateVersion(mavenVersion)

jar {
  manifest {
    attributes("Specificiation-Title": "CCL", "Specificiation-Version": version, "Implementation-Version": version)
  }
}

java {
  withSourcesJar()
  withJavadocJar()
}

// Sonatype / Maven Central via Nexus Publish Plugin
nexusPublishing {
  repositories {
    sonatype {
      nexusUrl = uri('https://ossrh-staging-api.central.sonatype.com/service/local/')
      snapshotRepositoryUrl = uri('https://central.sonatype.com/repository/maven-snapshots/')
      username = System.getenv('CENTRAL_TOKEN_USER')
      password = System.getenv('CENTRAL_TOKEN_PASS')
    }
  }
}

tasks.matching { it.name.contains('publishToSonatype') }.configureEach {
  onlyIf { isReleasable }
}
tasks.matching { it.name.contains('closeSonatype') || it.name.contains('releaseSonatype') || it.name.contains('closeAndReleaseSonatype') }.configureEach {
  onlyIf { isReleasable && currentBranch == 'master' }
}

publishing {
  repositories {
    maven {
      name = 'cloudsmith'
      def releasesRepoUrl = "https://api-g.cloudsmith.io/maven/cinchapi/open-source/"
      def snapshotsRepoUrl = "https://api-g.cloudsmith.io/maven/cinchapi/open-source-snapshots/"
      url = (isReleasable && !mavenVersion.endsWith('SNAPSHOT')) ? releasesRepoUrl : snapshotsRepoUrl
      credentials {
        username = System.getenv('CLOUDSMITH_API_USER')
        password = System.getenv('CLOUDSMITH_API_KEY')
      }
    }
  }
  publications {
    maven(MavenPublication) {
      from components.java
      groupId group
      artifactId project.name
      version mavenVersion
      pom {
        name = project.name
        description = 'The official specification and library for the Concourse Criteria Language'
        url = 'https://github.com/cinchapi/ccl'
        inceptionYear = '2015'
        licenses {
          license {
            name = 'Apache-2.0'
            url = 'https://spdx.org/licenses/Apache-2.0.html'
          }
        }
        developers {
          developer {
            id = 'jnelson'
            name = 'Jeff Nelson'
          }
        }
        scm {
          connection = 'scm:git:https://github.com/cinchapi/ccl.git'
          developerConnection = 'scm:git:ssh://github.com/cinchapi/ccl.git'
          url = 'https://github.com/cinchapi/ccl'
        }
      }
    }
  }
}

signing {
  required { isReleasable && !mavenVersion.endsWith('SNAPSHOT') }
  sign publishing.publications.maven
}

test {
  testLogging {
    showStandardStreams = true
  }
}

repositories {
  mavenCentral()
  maven {
    url "https://packages.cinchapi.com/public/open-source/maven/"
  }
  maven {
    url "https://packages.cinchapi.com/public/open-source-snapshots/maven/"
  }
  maven {
    url "https://packages.cinchapi.com/public/platform/maven/"
  }
  maven {
    url "https://packages.cinchapi.com/public/platform-snapshots/maven/"
  }
  maven {
    url "https://packages.cinchapi.com/public/enterprise/maven/"
    credentials {
      username = System.getenv('CLOUDSMITH_API_USER')
      password = System.getenv('CLOUDSMITH_API_KEY')
    }
  }
  maven {
    url "https://packages.cinchapi.com/public/enterprise-snapshots/maven/"
    credentials {
      username = System.getenv('CLOUDSMITH_API_USER')
      password = System.getenv('CLOUDSMITH_API_KEY')
    }
  }
}

ext.concourseVersion = '0.12.0'

dependencies {
  implementation 'com.google.code.findbugs:jsr305:2.0.1'
  implementation 'com.google.guava:guava:25.1-jre'
  implementation 'com.joestelmach:natty:0.13'
  implementation (group: 'com.cinchapi', name: 'accent4j', version: '1.6.1', changing:true) {
    exclude group: 'com.google.guava', module: 'guava'
  }
  implementation 'joda-time:joda-time:2.2'

  testImplementation 'junit:junit:4.11'
  testImplementation (group: 'com.cinchapi', name: 'concourse-driver-java', version: concourseVersion) {
      exclude group: 'com.cinchapi', module: 'ccl'
  }
}

task generateJavaCCParser(type: Exec) {
  commandLine './javacc-parser-generator.sh', 'generate', '--source', 'grammar/grammar.jjt', '--out', 'src/main/java/com/cinchapi/ccl/generated'
}

compileJava.dependsOn generateJavaCCParser
eclipseClasspath.dependsOn generateJavaCCParser
