/* Generated By:JavaCC: Do not edit this line. GrammarTreeConstants.java Version 7.0.3 */
package com.cinchapi.ccl.generator;

public interface GrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCONJ = 2;
  public int JJTRELATIONALEXPRESSION = 3;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Conj",
    "RelationalExpression",
  };
}
/* JavaCC - OriginalChecksum=28e20191c1057436083064e82a3c2edd (do not edit this line) */
