/* Generated By:JavaCC: Do not edit this line. GrammarVisitor.java Version 7.0.4 */
public interface GrammarVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTRelationalExpression node, Object data);
}
/* JavaCC - OriginalChecksum=692d72f0fba8ba9ae98e37bb876b4b0d (do not edit this line) */
