/* Generated By:JavaCC: Do not edit this line. GrammarVisitor.java Version 7.0.3 */
package com.cinchapi.ccl.generator;

public interface GrammarVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTConj node, Object data);
  public Object visit(ASTRelationalExpression node, Object data);
}
/* JavaCC - OriginalChecksum=f61e53ab9c2e27141144fae83f3fb2eb (do not edit this line) */
