/* Generated By:JavaCC: Do not edit this line. GrammarDefaultVisitor.java Version 7.0.3 */
package com.cinchapi.ccl.generator;

public class GrammarDefaultVisitor implements GrammarVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTConj node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRelationalExpression node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=ab2b631a6af3105b63f0cee2a905ce47 (do not edit this line) */
