package com.cinchapi.ccl;

import com.cinchapi.ccl.grammar.PostfixNotationSymbol;
import com.cinchapi.ccl.grammar.Symbol;
import com.cinchapi.ccl.syntax.AbstractSyntaxTree;
import com.cinchapi.ccl.type.Operator;
import com.cinchapi.ccl.v2.generated.ASTStart;
import com.cinchapi.ccl.v2.generated.Grammar;
import com.cinchapi.ccl.v2.generated.GrammarInfixVisitor;
import com.cinchapi.ccl.v2.generated.GrammarPostfixVisitor;
import com.cinchapi.ccl.v2.generated.GrammarTreeVisitor;
import com.cinchapi.ccl.v2.generated.SimpleNode;
import com.google.common.base.Throwables;
import com.google.common.collect.Multimap;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Queue;
import java.util.function.Function;

/**
 * This parser utilizes {@link Grammar} which is grammar generated by JavaCC
 */
public class JavaCCParser extends Parser {

    private final Function<String, Object> valueTransformFunction;
    private final Function<String, Operator> operatorTransformFunction;

    /**
     * Construct a new instance.
     *
     * @param ccl the ccl query to parse
     * @param valueTransformFunction value function
     * @param operatorTransformFunction operator function
     */
    protected JavaCCParser(String ccl,
            Function<String, Object> valueTransformFunction,
            Function<String, Operator> operatorTransformFunction) {
        super(ccl, null);
        this.valueTransformFunction = valueTransformFunction;
        this.operatorTransformFunction = operatorTransformFunction;
    }

    /**
     * Construct a new instance.
     *
     * @param ccl the ccl query to parse
     * @param data the local data
     * @param valueTransformFunction value function
     * @param operatorTransformFunction operator function
     */
    protected JavaCCParser(String ccl, Multimap<String, Object> data,
            Function<String, Object> valueTransformFunction,
            Function<String, Operator> operatorTransformFunction) {
        super(ccl, data);
        this.valueTransformFunction = valueTransformFunction;
        this.operatorTransformFunction = operatorTransformFunction;
    }

    @SuppressWarnings("unchecked")
    @Override
    public Queue<PostfixNotationSymbol> order() {
        try {
            InputStream stream = new ByteArrayInputStream(
                    ccl.getBytes(StandardCharsets.UTF_8.name()));
            Grammar grammar = new Grammar(stream);

            //AbstractSyntaxTree tree = grammar.generateAST();

            /*
            Visitor visitor = new Visitor<Queue<PostfixNotationSymbol>>() {
                Queue<PostfixNotationSymbol> symbols = new LinkedList<>();

                @Override
                public Queue<PostfixNotationSymbol> visit(AbstractSyntaxTree tree,
                        Object... data) {
                    for(AbstractSyntaxTree child : tree.children()) {
                        child.accept(this, data);
                    }
                    return symbols;
                }

                @Override
                public Queue<PostfixNotationSymbol> visit(BaseConjunctionTree tree, Object... data) {
                    tree.left().accept(this, data);
                    tree.right().accept(this, data);
                    symbols.add((PostfixNotationSymbol) tree.root());
                    return symbols;
                }

                @Override
                public Queue<PostfixNotationSymbol> visit(BaseExpressionTree tree, Object... data) {
                    symbols.add((PostfixNotationSymbol) tree.root());
                    return symbols;
                }
            };
            //tree.accept(visitor);
            */

            SimpleNode tree = grammar.generateAST();
            GrammarPostfixVisitor visitor = new GrammarPostfixVisitor(this, data);
            return (Queue<PostfixNotationSymbol>) tree.jjtAccept(visitor,
                    null);
        }
        catch (Exception exception) {
            Throwables.propagate(exception);
        }
        return null;
    }

    @SuppressWarnings("unchecked")
    @Override
    public AbstractSyntaxTree parse() {
        try {
            InputStream stream = new ByteArrayInputStream(
                    ccl.getBytes(StandardCharsets.UTF_8.name()));
            Grammar grammar = new Grammar(stream);

            ASTStart tree = grammar.generateAST();

            GrammarTreeVisitor visitor = new GrammarTreeVisitor(this, data);
            return (AbstractSyntaxTree) tree.jjtAccept(visitor, null);
        }
        catch (Exception exception) {
            Throwables.propagate(exception);
        }
        return null;
    }

    @SuppressWarnings("unchecked")
    @Override
    public List<Symbol> tokenize() {
        try {
            InputStream stream = new ByteArrayInputStream(
                    ccl.getBytes(StandardCharsets.UTF_8.name()));
            Grammar grammar = new Grammar(stream);
            SimpleNode tree = grammar.generateAST();

            GrammarInfixVisitor visitor = new GrammarInfixVisitor(this ,data);
            return (List<Symbol>) tree.jjtAccept(visitor, null);
        }
        catch (Exception exception) {
            Throwables.propagate(exception);
        }
        return null;
    }

    @Override
    public Operator transformOperator(String token) {
        return operatorTransformFunction.apply(token);
    }

    @Override
    public Object transformValue(String token) {
        return valueTransformFunction.apply(token);
    }
}
